server:
  port: 9301

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: user-api
#          uri: http://www.xujin.org:80/
#          predicates:
#            - Path=/xujin

logging:
  level:
    org.springframework.cloud.gateway: debug
