server:
  port: 9301

spring:
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: lb://lb-service-user
          predicates:
            - Path=/user/**

lb-service-user:
  ribbon:
    listOfServers: service-user1:9001, service-user2:9002, service-user3:9003
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

logging:
  level:
    org.springframework.cloud.gateway: debug
