spring:
  profiles:
    active: dev
  application:
    name: service-user

server:
  port: 9001

eureka:
  client:
    service-url:
      #      defaultZone: http://registry-server1:9101/eureka/,http://registry-server2:9102/eureka/,http://registry-server3:9103/eureka/
      defaultZone: http://registry-server1:9100/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"