spring:
  profiles:
    active: dev
  application:
    name: service-user

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"